### ISSUE TITLE
Clustering should be enabled 

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#76] opened 2015-10-14 11:04 UTC
Clustering should be enabled when checking "View Observed Species" especially for a dense one such as red maple.

**Comment by jduggan1** [comment] 2015-10-14 15:54
marking as duplicate of: https://github.com/nationalparkservice/npmap-species/issues/11

**Comment by jduggan1** [comment] 2016-01-25 20:29
Closing duplicate.

**Closed by jduggan1** 2016-01-25 20:29 UTC
Labels: bug, duplicate
