### ISSUE TITLE
Species search bar functionality

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#54] opened 2015-06-10 15:39 UTC
If a species (species 2) is chosen to compare to the original (species 1), it should be removed from the list of potential species to choose for species 3. 

The image below also shows a text rendering issue-- I assume that the species name was longer than allowed and therefore shows up oddly. We need to plan for this and include code that truncates the species name and inserts an ellipsis or some other placeholder. 

![10](https://cloud.githubusercontent.com/assets/8036575/8086791/34a1865c-0f65-11e5-962a-8762831697ac.PNG)

**Comment by jduggan1** [comment] 2015-07-06 22:17
Kendra, I've fixed the first issue.  The second I cannot reproduce on my end (even the longest names fit into my dropdowns.  I did find a bug related to this, and I'm hopeful that it's now fixed.  Could you try it again and let me know if it's still a problem?

**Comment by KendraStraub** [comment] 2015-07-07 12:49
I still have the same issue. Did you try to execute the same search? Quercus rubra> species with similar environment? 

![2](https://cloud.githubusercontent.com/assets/8036575/8546349/16fb2f24-2485-11e5-9bb3-bf4f1a282d75.PNG)

**Comment by jduggan1** [comment] 2015-07-08 01:00
Ah, I owe you an apology, as I am an idiot.  I was looking at the distribution results instead of environment.  I've added code to replace the end of strings longer than 30 characters with an ellipsis.  To compensate for the potential loss of information, those strings which are truncated now have a tooltip when you hover over them to show the full name.

This should take care of any strings (so I'm closing this issue), but if you find any cases where a string is still too long for the box please let me know.

**Closed by jduggan1** 2015-07-08 01:00 UTC
Labels: bug, enhancement
