### ISSUE TITLE
Compare with another species in park

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#33] opened 2015-06-10 11:15 UTC
Compare with another species in park is really confusing...allows a compare such as "SEARCH> SWEET-GUM > GRAND GLOBE > GREEN FROG > TULIPTREE > POVERTY WILD OAT" yet color legend shows only 3 species.....should be limited to only compare 3 species in park. Pick list also seems odd, typing a few letters, the typed letters persist....

**Comment by jduggan1** [comment] 2015-06-15 04:44
I need to redo this portion of the search tool, so I'm marking it as a duplicate of the issue I have for that.

**Comment by jduggan1** [comment] 2015-10-08 01:46
This issue is gone with the updated site.

**Closed by jduggan1** 2015-10-08 01:46 UTC
Labels: bug, duplicate, question
