### ISSUE TITLE
Spatial search does not work

### ISSUE THREAD

**Issue by tpcolson** [nationalparkservice/npmap-species#37] opened 2015-06-10 11:21 UTC
The search by area on map does not work....

**Comment by jduggan1** [comment] 2015-06-15 04:51
This is my largest remaining hurdle. I am not sure how soon I will be able to get to it, as I want to finish everything else first (I will go for the lower hanging fruit first). I've got an issue for this already, so I'm marking this as a duplicate.

**Comment by jduggan1** [comment] 2015-08-17 16:21
Duplicate of https://github.com/nationalparkservice/npmap-species/issues/7

**Closed by jduggan1** 2015-08-17 16:21 UTC
Labels: bug, duplicate
